name: Build Auth Login Lambda

on:
  push:
    branches: [main, stage]
    paths:
      - 'lambdas/auth-login/**'
      - '.github/workflows/build-auth-login.yml'
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-auth-login:
    runs-on: ubuntu-latest
    outputs:
      source_code_hash: ${{ steps.hash.outputs.hash }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: lambdas/auth-login

      - name: Build Lambda
        run: npx esbuild src/index.ts --bundle --platform=node --target=node20 --outfile=dist/index.js
        working-directory: lambdas/auth-login

      - name: Zip Lambda
        run: zip -j function.zip dist/index.js
        working-directory: lambdas/auth-login

      - name: Generate source code hash
        id: hash
        run: |
          HASH=$(shasum -a 256 lambdas/auth-login/function.zip | cut -d ' ' -f 1 | xxd -r -p | base64)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          BRANCH=${GITHUB_REF##*/}
          aws s3 cp lambdas/auth-login/function.zip s3://lambdas-artifacts-$BRANCH/auth-login/$BRANCH/function.zip